
default: &default
  adapter: postgresql
  encoding: unicode
  username: ycarorailsrb
  password: 5655
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_development

  
test:
  <<: *default
  database: ecommerce_test


production:
  <<: *default
  database: ecommerce_production
